### Tensors
- specialized data structure that are very similar to array and matrices. In pytorch, we use tensors to encode the inputs and outputs of a model as well as the model's parameters.

- Tensors are similar to  Numpy's ndarrays except that tensors can run on gpu or other hardware accelerators. In fact, tensoras and numpy arrays canoften share the same underlying memory, eliminating the need to copy data. 

- Tensors are also optimized for automatic differentiation. 

In [2]:
import torch
import numpy as np

### Initializing a tensor
Tensor can be initialized in various ways: 

In [5]:
# directly from data 
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [6]:
# from numpy array 
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [8]:
# from another tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"One tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data,dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

One tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7640, 0.6591],
        [0.8233, 0.8172]]) 



In [9]:
# with random or constant values
shape = (2,3)
rand_tensor  = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print("Random Tensor",rand_tensor)
print("Ones Tensor",ones_tensor)
print("Zeros Tensor",zeros_tensor)

Random Tensor tensor([[0.3783, 0.9285, 0.8441],
        [0.6236, 0.2414, 0.0519]])
Ones Tensor tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Attributes of a tensor
Tensor attributes describe their shape, datatype, and the device on which they are stored.


In [10]:
tensor = torch.rand(3,4)
print("Shape: ",tensor.shape)
print("Datatype: ",tensor.dtype)
print("Device used: ",tensor.device)

Shape:  torch.Size([3, 4])
Datatype:  torch.float32
Device used:  cpu


### Operations on tensor

- Over 1200 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described here.

- Each of these operations can be run on the CPU and Accelerator such as CUDA, MPS, MTIA, or XPU. If you’re using Colab, allocate an accelerator by going to Runtime > Change runtime type > GPU.

- By default, tensors are created on the CPU. We need to explicitly move tensors to the accelerator using .to method (after checking for accelerator availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [11]:
# we move our tensor to the curent accelerator if available 
if torch.accelerator.is_available():
    tensor = torch.to(torch.accelerator.current_aqccelerator())

### Standard numpy-like indexing and slicing:



In [12]:
tensor = torch.randn(4,4)
print("First row ", tensor[0])
print("First Coloumn ", tensor[:,0])
print("Last Column: ",tensor[...,-1])
tensor[:,1] = 0
print(tensor)


First row  tensor([ 1.0896,  0.3259, -1.1808, -0.9351])
First Coloumn  tensor([ 1.0896, -0.6125,  1.3212,  0.1840])
Last Column:  tensor([-0.9351, -0.5585, -0.1176, -0.7295])
tensor([[ 1.0896,  0.0000, -1.1808, -0.9351],
        [-0.6125,  0.0000,  0.4371, -0.5585],
        [ 1.3212,  0.0000, -1.2357, -0.1176],
        [ 0.1840,  0.0000, -1.0049, -0.7295]])


- Joining tensors You can use torch.cat to concatenate a sequence of tensors along a given dimension. See also torch.stack, another tensor joining operator that is subtly different from torch.cat.

In [14]:
t1 = torch.cat(
    [tensor, tensor, tensor], dim=1
)  # Since dim=1 means columns, PyTorch puts the tensors side-by-side:
print(t1)

tensor([[ 1.0896,  0.0000, -1.1808, -0.9351,  1.0896,  0.0000, -1.1808, -0.9351,
          1.0896,  0.0000, -1.1808, -0.9351],
        [-0.6125,  0.0000,  0.4371, -0.5585, -0.6125,  0.0000,  0.4371, -0.5585,
         -0.6125,  0.0000,  0.4371, -0.5585],
        [ 1.3212,  0.0000, -1.2357, -0.1176,  1.3212,  0.0000, -1.2357, -0.1176,
          1.3212,  0.0000, -1.2357, -0.1176],
        [ 0.1840,  0.0000, -1.0049, -0.7295,  0.1840,  0.0000, -1.0049, -0.7295,
          0.1840,  0.0000, -1.0049, -0.7295]])


### Arithmetic operations



In [18]:
y1 = tensor @ tensor.T
print(y1)
y2 = tensor.matmul(tensor.T)
print(y2)
y3 = torch.rand_like(y1)
print(y3)
torch.matmul(tensor,tensor.T,out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)

tensor([[ 3.4561, -0.6612,  3.0087,  2.0693],
        [-0.6612,  0.8782, -1.2836, -0.1444],
        [ 3.0087, -1.2836,  3.2862,  1.5706],
        [ 2.0693, -0.1444,  1.5706,  1.5759]])
tensor([[ 3.4561, -0.6612,  3.0087,  2.0693],
        [-0.6612,  0.8782, -1.2836, -0.1444],
        [ 3.0087, -1.2836,  3.2862,  1.5706],
        [ 2.0693, -0.1444,  1.5706,  1.5759]])
tensor([[0.5367, 0.2326, 0.9688, 0.1935],
        [0.0171, 0.3956, 0.1502, 0.6636],
        [0.7521, 0.3255, 0.9581, 0.0802],
        [0.0572, 0.5695, 0.7772, 0.0783]])


tensor([[1.1873, 0.0000, 1.3944, 0.8744],
        [0.3751, 0.0000, 0.1911, 0.3120],
        [1.7455, 0.0000, 1.5269, 0.0138],
        [0.0338, 0.0000, 1.0098, 0.5322]])

Single-element tensors If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

In [20]:
tensor

tensor([[ 1.0896,  0.0000, -1.1808, -0.9351],
        [-0.6125,  0.0000,  0.4371, -0.5585],
        [ 1.3212,  0.0000, -1.2357, -0.1176],
        [ 0.1840,  0.0000, -1.0049, -0.7295]])

In [21]:
agg = tensor.sum()
agg

tensor(-3.3428)

In [23]:
agg_item = agg.item()
agg_item

-3.342833995819092

In [26]:
type(agg_item)

float

### Inplace Operations
- changes the exising tensor directly ., instead of creating a new tensor
- Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y),x.t_(), will change x

In [27]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[ 1.0896,  0.0000, -1.1808, -0.9351],
        [-0.6125,  0.0000,  0.4371, -0.5585],
        [ 1.3212,  0.0000, -1.2357, -0.1176],
        [ 0.1840,  0.0000, -1.0049, -0.7295]]) 

tensor([[6.0896, 5.0000, 3.8192, 4.0649],
        [4.3875, 5.0000, 5.4371, 4.4415],
        [6.3212, 5.0000, 3.7643, 4.8824],
        [5.1840, 5.0000, 3.9951, 4.2705]])


### Bridge with numpy 
Ternsors ont he cpu and numpy arrayas can share their underlying memory locations and changing one will change the other

#### Tensor to numpy array 

In [ ]:
t = torch.ones(5)
print(f"t:{t}")
n = t.numpy()
print(f"n:{n}")

t:tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]


- A change in the tensor reflects in the NumPy array.



In [29]:
t.add_(1)
print(f"t:{t}")
print(f"n:{n}")

t:tensor([2., 2., 2., 2., 2.])
n:[2. 2. 2. 2. 2.]


#### NumPy array to Tensor

In [30]:
n = np.ones(5)
t = torch.from_numpy(n)

- Changes in the NumPy array reflects in the tensor.

In [31]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
